- name: Set up Ruby
  uses: ruby/setup-ruby@v1
  with:
    ruby-version: 2.7
    bundler-cache: true

- name: Build and deploy
  uses: helaili/jekyll-action@v2
  with:
    token: ${{ secrets.GITHUB_TOKEN }}